### ISSUE TITLE
[RFC] Add a "go-unit-tests" hook

### ISSUE THREAD

**Issue by cshamrick** [Bellese/pre-commit-golang#3]
Adding this RFC on behalf of @jduclos-bellese - we'd like to get feedback about whether we could add a `go-unit-tests` hook to this project. We could implement the hook similar to the `go-unit-tests` hook found in [dnephin/pre-commit-golang](https://github.com/dnephin/pre-commit-golang), which executes a `bash` script like this:

```bash
#!/usr/bin/env bash
FILES=$(go list ./...  | grep -v /vendor/)

go test -tags=unit -timeout 30s -short -v ${FILES}

returncode=$?
if [ $returncode -ne 0 ]; then
  echo "unit tests failed"
  exit 1
fi
```

**Comment by phillipjf** [comment]
This example script is pretty opinionated. We should decide if it's the opinion we want to enforce or if there's a better way to allow configuration on how to run tests. There's only a few issues on the original project but one already asks for a different way to do tests: https://github.com/dnephin/pre-commit-golang/issues/49

This suggests all tests to be tagged `unit` via [Build Constraints](https://golang.org/cmd/go/#hdr-Build_constraints). What if a project does not tag their tests? Or already uses another tag for managing tests?

If there really is a good "standard" for tests, we could drive towards that but I think, generally, any implementation may end up being too opinionated, and therefore, unused.

**Comment by cshamrick** [comment]
@phillipjf would it be of value to implement a generic, configurable/overridable solution for this? e.g.:

The default just runs tests without tags, etc.:

 ```yaml
 repos:
  - repo: git://github.com/bellese/pre-commit-golang
    rev: master
    hooks:
      - id: go-unit-tests
```

Or with `-tags` and `-timeout`:
 ```yaml
 repos:
  - repo: git://github.com/bellese/pre-commit-golang
    rev: master
    hooks:
      - id: go-unit-tests
        args: [-tags=unit, -timeout=30s]
```
